### ISSUE TITLE
Cross-compilation

### ISSUE THREAD

**Issue by pkerling** [NilsBrause/waylandpp#26]
I just remembered another thing that should probably be fixed before #25: @lrusak did some experimental LibreELEC builds with Kodi/Wayland and encountered the problem that at the moment cross-compiling waylandpp is not possible because the scanner is also compiled for the target instead of the host architecture (which makes it impossible to execute). libwayland also had issues with this for some time so we should not repeat that mistake :-)

Do you know how SCons handles this by any chance? I can try my hand at it, but I have zero SCons experience, mostly used CMake.

**Comment by NilsBrause** [comment]
I'd use two separate environments for the scanner and the libraries. The environment for the scanner would use the host compiler (which is g++ by default) and the environment for the libraries would use the cross compiler, which could be configured by environment variables such as CROSSCXX and CROSSCXXFLAGS.
I'll try to come up with something. :)

**Comment by NilsBrause** [comment]
I do not have a cross compiler at the moment, so please test d822b12e1aaa66e22d9b9568ecb5cd99fbda4bef.

**Comment by pkerling** [comment]
Wow that was quick and looks nice - I'll take a look at it, toolchain's building as we speak :-)

**Comment by pkerling** [comment]
Worked :+1: tried without egl though since I was too lazy to cross-compile mesa.

@lrusak Could you perhaps test this in the LibreELEC build?

**Comment by lrusak** [comment]
Yea I can do a test thanks!

**Comment by NilsBrause** [comment]
I assume the tests were successful, so I'll be closing this one.
