### ISSUE TITLE
Allow specifying libdir in SCons

### ISSUE THREAD

**Issue by candrews** [NilsBrause/waylandpp#30]
Some distributions use a libdir other that "lib" - it would be great if, similar to ROOT and PREFIX, LIBDIR could be specified (with a default value of "lib" of course).

**Comment by NilsBrause** [comment]
That is a good idea. While at it, I also added includedir, bindir and sharedir.

Fixed in 7d019009893e156de74b5fed7ae0895022907e6d.

**Comment by candrews** [comment]
Thank you!
