### ISSUE TITLE
cmake minimum version ?

### ISSUE THREAD

**Issue by ffontaine** [NilsBrause/waylandpp#64]
What is the rationale for bumping cmake version from 3.1 to 3.12 in https://github.com/NilsBrause/waylandpp/commit/af21eb9394d7e72022ff058cce67761554d0a1f4?

Could this requirement be lowered to 3.10 or 3.8?
I'm asking this question because we have build failures in buildroot because we enforce only cmake 3.8 or 3.10 for our users: http://autobuild.buildroot.org/results/587/587fb44ea2272bd134262716870f5ad36a18661d/build-end.log.

**Comment by NilsBrause** [comment]
The reason was the usage of target_link_options(). In the latest commit a39c0c115e19150551c01b04a5e903376633e771 I made its usage optional lowering the minimum cmake version to 3.4. I hope this helps.
