### ISSUE TITLE
0.2.9 broke ABI

### ISSUE THREAD

**Issue by mapreri** [NilsBrause/waylandpp#69]
Hi,

commit https://github.com/NilsBrause/waylandpp/commit/87fb88b93b0b24517388c6b38cb26638b5cebf86 broke the ABI, as re-defining a function as `const` will drop it from the symbols table.

See https://bugs.debian.org/1006812 for a downstream bug showing how a linked program stopped working.

Please either:
1) revert that commit
2) add non-const overloaded variant to retain the ABI
3) bump the SONAME

Thank you for considering.

**Comment by basilgello** [comment]
@NilsBrause There is another bugreport om Kodi forums, this time on Ubuntu with the following symbol:

```
_ZN7wayland9display_tC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

which demangles to:

```
wayland::display_t::display_t(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
```

It is a constructor and I don't see it in the reverted commit.
