### ISSUE TITLE
Please update wayland.xml protocol

### ISSUE THREAD

**Issue by selairi** [NilsBrause/waylandpp#70]
Hi,

I was trying to run a Wayland tool and I found this error output:
`
interface 'wl_output' has no event 4
`
I found that "wayland.xml" of my system is newer than version included in waylandpp. I recompiled waylandpp with new version of "wayland.xml" and it worked properly.

Can "wayland.xml" updated?

Thanks for your work.

**Comment by NilsBrause** [comment]
wayland.xml has been updated in commit c9e2ce154d3c244ecb534929e336097e7641a203.

**Comment by selairi** [comment]
Thanks for your good work.
