### ISSUE TITLE
interface 'xdg_toplevel' has no event 3

### ISSUE THREAD

**Issue by PatchByte** [NilsBrause/waylandpp#81]
I have no idea what this error means, but I guess waylandpp might have an issue with the compositor I am using.
I am using mutter, and I am trying to run the shm example.
(I also might just be dumb.)

**Comment by tanxiang** [comment]
try 
wayland-scanner++  /usr/share/wayland-protocols/stable/xdg-shell/xdg-shell.xml xdg-shell.hpp xdg-shell.cpp
recompile xdg-shell.cpp and link into  shm example.
